---
title: "Advanced R 研讨"
subtitle: "水平测试"
author: "罗智超Rokia.org"
output: 
  pdf_document: 
    fig_caption: yes
    keep_tex: yes
    latex_engine: xelatex
    toc: yes
header-includes:
- \usepackage{xeCJK}
---


# 水平测试

请独立完成以下测试，并记录完成以下每道测试所花费的时间

## 向量运算

- 测试：编写一个函数findNum(y,l)计算在y向量中数字1连续出现l次的位置。

```{r,eval=FALSE}
#y<- c(1,0,0,1,1,1,0,1,1)
#计算结果为：c(4,5,8)
findNum<-function(y,l){
  #y是输入向量
  #l是1连续出现的长度
        identify = NULL
        for(i in 1:(length(y)-l+1)){
                y.sub = y[(i:(i+l-1))]
                id = identical(y.sub,rep(1,l))
                identify = c(identify,id)
        }
        which(identify == TRUE)
}

```


## 数据结构

- 测试：计算每天最低气温和最高气温的差值

```{r,eval=FALSE}
raw <- read.delim("data/weather.txt",check.names = F, na.strings = ".")

library(reshape)
raw.melt = melt(raw, id = c("year","month","element"))
raw.melt$variable = as.numeric(raw.melt$variable)
date = paste(raw.melt$year,raw.melt$month,raw.melt$variable,sep = "-")
raw.melt$Date = as.Date(date)
raw.melt = raw.melt[!is.na(raw.melt$Date),]
raw.new = raw.melt[,c("Date","element","value")]

raw.wide = reshape(raw.new,v.names = "value",idvar = "Date",timevar = "element",direction = "wide")
raw.wide$change = raw.wide$value.tmax-raw.wide$value.tmin
```

## 分组处理

- 测试：计算每个航空公司(UniqueCarrier)每个月到达延误时间(ArrDelay)的十分位(quantile)的均值。

```{r,eval=FALSE}
#计算hfflights
library(hflights)
str(hflights)

hflights.new = select(hflights,Month,UniqueCarrier,ArrDelay)
identify = as.factor(paste(hflights.new$Month,hflights.new$UniqueCarrier,sep="."))
results = tapply(hflights.new$ArrDelay,identify,function(x){quantile(x,seq(0,1,0.1),na.rm = TRUE)})

results.dataframe = data.frame(Reduce(rbind, results))
row.names(results.dataframe) = unique(identify)
colnames(results.dataframe) = paste(seq(0,100,10),"%",sep = "")
```

